package com.devluanpaiva.controle_de_remedios.modules.report.pdf;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfWriter;

import com.devluanpaiva.controle_de_remedios.shared.exceptions.BusinessException;

/**
 * Builds formal, letterhead-style PDF reports (ChegaMed logo, company/issuer
 * info, a data table and a page footer) shared by every report generated by
 * {@link com.devluanpaiva.controle_de_remedios.modules.report.service.ReportService}.
 */
@Component
public class ReportPdfBuilder {
    private static final DateTimeFormatter TIMESTAMP_FORMAT = DateTimeFormatter.ofPattern("dd/MM/yyyy 'às' HH:mm");

    private static final Color BRAND_COLOR = new Color(0x0F, 0x62, 0x5D);
    private static final Color ROW_ALTERNATE_BACKGROUND = new Color(0xF7, 0xFA, 0xFA);
    private static final Color BORDER_COLOR = new Color(0xD8, 0xE0, 0xDF);

    private final byte[] logoBytes;

    public ReportPdfBuilder() {
        this.logoBytes = loadLogo();
    }

    public byte[] build(
            String title,
            String companyName,
            String companyCnpj,
            String generatedByName,
            LocalDateTime generatedAt,
            String[] columnHeaders,
            float[] columnWidths,
            List<String[]> rows) {

        Document document = new Document(PageSize.A4, 40, 40, 40, 50);

        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            PdfWriter writer = PdfWriter.getInstance(document, outputStream);
            writer.setPageEvent(new FooterPageEvent(generatedAt));

            document.open();
            addLetterhead(document, title, companyName, companyCnpj, generatedByName, generatedAt);
            addTable(document, columnHeaders, columnWidths, rows);
            document.close();

            return outputStream.toByteArray();
        } catch (DocumentException | IOException ex) {
            throw new BusinessException(
                    HttpStatus.INTERNAL_SERVER_ERROR,
                    "Falha ao gerar relatório",
                    "REPORT_GENERATION_FAILED",
                    "report",
                    "Não foi possível gerar o documento PDF do relatório.");
        }
    }

    private byte[] loadLogo() {
        try (InputStream inputStream = new ClassPathResource("report/chegamed-logo.png").getInputStream()) {
            return inputStream.readAllBytes();
        } catch (IOException ex) {
            throw new IllegalStateException("Não foi possível carregar a logo do ChegaMed para o relatório.", ex);
        }
    }

    private void addLetterhead(
            Document document,
            String title,
            String companyName,
            String companyCnpj,
            String generatedByName,
            LocalDateTime generatedAt) throws DocumentException, IOException {

        Image logo = Image.getInstance(logoBytes);
        logo.scaleToFit(140, 70);
        logo.setAlignment(Element.ALIGN_LEFT);
        document.add(logo);

        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Font.BOLD, BRAND_COLOR);
        Paragraph titleParagraph = new Paragraph(title, titleFont);
        titleParagraph.setSpacingBefore(14f);
        titleParagraph.setSpacingAfter(10f);
        document.add(titleParagraph);

        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Font.BOLD, Color.DARK_GRAY);
        Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Font.NORMAL, Color.DARK_GRAY);

        document.add(infoLine("Empresa: ", companyName, labelFont, valueFont));

        if (companyCnpj != null && !companyCnpj.isBlank()) {
            document.add(infoLine("CNPJ: ", formatCnpj(companyCnpj), labelFont, valueFont));
        }

        document.add(infoLine("Emitido por: ", generatedByName, labelFont, valueFont));

        Paragraph generatedAtParagraph =
                infoLine("Emitido em: ", generatedAt.format(TIMESTAMP_FORMAT), labelFont, valueFont);
        generatedAtParagraph.setSpacingAfter(16f);
        document.add(generatedAtParagraph);
    }

    private Paragraph infoLine(String label, String value, Font labelFont, Font valueFont) {
        Paragraph paragraph = new Paragraph();
        paragraph.add(new Chunk(label, labelFont));
        paragraph.add(new Chunk(value, valueFont));
        paragraph.setSpacingAfter(2f);
        return paragraph;
    }

    private String formatCnpj(String cnpj) {
        if (cnpj == null || cnpj.length() != 14) {
            return cnpj;
        }

        return cnpj.substring(0, 2) + "." + cnpj.substring(2, 5) + "." + cnpj.substring(5, 8)
                + "/" + cnpj.substring(8, 12) + "-" + cnpj.substring(12, 14);
    }

    private void addTable(Document document, String[] columnHeaders, float[] columnWidths, List<String[]> rows)
            throws DocumentException {

        PdfPTable table = new PdfPTable(columnWidths);
        table.setWidthPercentage(100);
        table.setHeaderRows(1);

        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Font.BOLD, Color.WHITE);

        for (String header : columnHeaders) {
            PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
            cell.setBackgroundColor(BRAND_COLOR);
            cell.setPadding(6f);
            cell.setBorderColor(BORDER_COLOR);
            table.addCell(cell);
        }

        Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9.5f, Font.NORMAL, Color.BLACK);

        if (rows.isEmpty()) {
            PdfPCell emptyCell = new PdfPCell(new Phrase("Nenhum registro encontrado.", cellFont));
            emptyCell.setColspan(columnHeaders.length);
            emptyCell.setPadding(10f);
            emptyCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            emptyCell.setBorderColor(BORDER_COLOR);
            table.addCell(emptyCell);
        } else {
            addRows(table, rows, cellFont);
        }

        document.add(table);
    }

    private void addRows(PdfPTable table, List<String[]> rows, Font cellFont) {
        int rowIndex = 0;

        for (String[] row : rows) {
            Color background = rowIndex % 2 == 0 ? Color.WHITE : ROW_ALTERNATE_BACKGROUND;

            for (String value : row) {
                PdfPCell cell = new PdfPCell(new Phrase(value != null ? value : "-", cellFont));
                cell.setBackgroundColor(background);
                cell.setPadding(5.5f);
                cell.setBorderColor(BORDER_COLOR);
                table.addCell(cell);
            }

            rowIndex++;
        }
    }

    private static final class FooterPageEvent extends PdfPageEventHelper {
        private static final DateTimeFormatter FOOTER_TIMESTAMP_FORMAT = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        private final Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Font.NORMAL, Color.GRAY);
        private final String generatedAtLabel;

        private FooterPageEvent(LocalDateTime generatedAt) {
            this.generatedAtLabel = "Documento gerado eletronicamente pelo sistema ChegaMed em "
                    + generatedAt.format(FOOTER_TIMESTAMP_FORMAT);
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte contentByte = writer.getDirectContent();
            contentByte.setFontAndSize(footerFont.getBaseFont(), footerFont.getSize());

            contentByte.showTextAligned(
                    Element.ALIGN_LEFT, generatedAtLabel, document.left(), document.bottom() - 20, 0);

            contentByte.showTextAligned(
                    Element.ALIGN_RIGHT,
                    "Página " + writer.getPageNumber(),
                    document.right(),
                    document.bottom() - 20,
                    0);
        }
    }
}
